// Mocks generated by Mockito from annotations
// in aevon/test/features/auth/domain/usecases/sign_in_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i6;

import 'package:aevon/core/shared/auth_session/presentation/cubit/auth_session_cubit.dart'
    as _i10;
import 'package:aevon/core/shared/auth_session/presentation/cubit/auth_session_state.dart'
    as _i4;
import 'package:aevon/core/shared/data/model/result.dart' as _i2;
import 'package:aevon/features/auth/data/models/auth_request.dart' as _i8;
import 'package:aevon/features/auth/data/models/user_model.dart' as _i11;
import 'package:aevon/features/auth/domain/entities/sign_in_entity.dart' as _i7;
import 'package:aevon/features/auth/domain/repositories/sign_in_repo.dart'
    as _i3;
import 'package:aevon/features/auth/domain/usecases/sign_in_use_case.dart'
    as _i5;
import 'package:aevon/features/auth/domain/usecases/sign_up_use_case.dart'
    as _i9;
import 'package:bloc/bloc.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepo_1 extends _i1.SmartFake implements _i3.AuthRepo {
  _FakeAuthRepo_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthSessionState_2 extends _i1.SmartFake
    implements _i4.AuthSessionState {
  _FakeAuthSessionState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SignInUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInUseCase extends _i1.Mock implements _i5.SignInUseCase {
  MockSignInUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.Result<_i7.AuthEntity>> call(_i8.SignInRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#call, [request]),
            returnValue: _i6.Future<_i2.Result<_i7.AuthEntity>>.value(
              _FakeResult_0<_i7.AuthEntity>(
                this,
                Invocation.method(#call, [request]),
              ),
            ),
          )
          as _i6.Future<_i2.Result<_i7.AuthEntity>>);
}

/// A class which mocks [SignUpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpUseCase extends _i1.Mock implements _i9.SignUpUseCase {
  MockSignUpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.AuthRepo get authRepo =>
      (super.noSuchMethod(
            Invocation.getter(#authRepo),
            returnValue: _FakeAuthRepo_1(this, Invocation.getter(#authRepo)),
          )
          as _i3.AuthRepo);

  @override
  _i6.Future<_i2.Result<_i7.AuthEntity>> call(_i8.SignUpRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#call, [request]),
            returnValue: _i6.Future<_i2.Result<_i7.AuthEntity>>.value(
              _FakeResult_0<_i7.AuthEntity>(
                this,
                Invocation.method(#call, [request]),
              ),
            ),
          )
          as _i6.Future<_i2.Result<_i7.AuthEntity>>);
}

/// A class which mocks [AuthSessionCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthSessionCubit extends _i1.Mock implements _i10.AuthSessionCubit {
  MockAuthSessionCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.AuthSessionState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthSessionState_2(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i4.AuthSessionState);

  @override
  _i6.Stream<_i4.AuthSessionState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i4.AuthSessionState>.empty(),
          )
          as _i6.Stream<_i4.AuthSessionState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> syncUserData() =>
      (super.noSuchMethod(
            Invocation.method(#syncUserData, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> fetchSession() =>
      (super.noSuchMethod(
            Invocation.method(#fetchSession, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveSession({
    required _i11.User? user,
    required String? token,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveSession, [], {#user: user, #token: token}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateUser(_i11.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [user]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> clearSession() =>
      (super.noSuchMethod(
            Invocation.method(#clearSession, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void emit(_i4.AuthSessionState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i12.Change<_i4.AuthSessionState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
